---
- name: test playbook
  hosts: all
  tasks:
  - name: run command
    shell: yum clean all && yum repolist
    ignore_errors: true
    register: yum
  - name: debug register 
    debug:
      var:  yum
  - name: use when yum failed
    debug:
      msg: failed yum
    when: yum.rc == "0"
  
  
...
